language: node_js
node_js:
- '8'
- '9'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - g++-4.8
    - google-chrome-stable
before_install:
- google-chrome --product-version
- export DISPLAY=:99.0
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1600x1024x16
- cd .. && git clone https://github.com/sitespeedio/sitespeed.io.git
- cd sitespeed.io && npm install -g && cd ../plugin-lighthouse
script:
- npm run lint
- sitespeed.io --plugins.add ./lib/ -n 1
notifications:
  slack:
    secure: GAuuPF+dRE83GytvQlYhQ5NFtXjaGQDu42leJX/l1bZbT13lhAkqxc2kttdTZp7+Rf0Evk02cuYVbTl2ahatnWzXNkKRNO+IQRmx+1mwOcUAEeWtrfLo2L4BGWfsh6jxxskXDb7QJyPWXhwrM2mwaQ3JKZDdEKIhCoeQHHljZ8o1hTHrl8e0mdmqsXtnbatn/Ue0pE3/ZWMWXZXBN25NK6rHEQCRhMe5wvp32ci7RxnouHbulN+Bopem96LMbG1KJVoLkqqEsMcNBA58XERdYgvRshg/gQzimT5JeTS52vkMA+HLR17qmavm2TsB8f7axIsx1WxdI4zedCSPXG7kQlfgkbK87Jfq2IxHll65/BCGEpKA/7KwZbTKGQp1PjBzZnYasTGlvrRdtBGJYI89Im0KQ7ZP6zBHPOrjGkYea/zv/HB38u5G9TyXm7orxzj5HSY01Bt2r20korcjSOcPTSHyNSbbxn45UUSclyx9zyjlOmk6R2sPbOUIQQMWHm1KpGXwe+prpIMwOIybi6jvIvQkPSKqtl7yLe9oqX2iFJQeBOaFWk9wy+gEMRgP14hCtHI2wBLSRLSzqNgudaLIKOpyzWmqNJIP8Bt+HCSpxYZy/Wd6A1pJoYP6k5mGtWda1/PjYtX8TcHOyE5PmCfSt1nTMAdDBN5mf9BFz0dQLqE=
env:
  global:
    secure: vZZocQuMGxU85J1a5Zh6H3IceHIe++SfctlKcb4YOVgTwxv0IrWqRCe/EXpLLTeVkXHVuXP37nmfxo5k3piwP4c9plvYX7tTsXw6KT4LuJIQAaxMJjBQdoIfnU8SO/bnCMpElUTAyRYFflolNU4Edc7Cg3qJu0WGWTV3cNTSmobTRnN6YnMw4qP2gC5O9FeaCxhL2+mNDYx7FSwQkxqIbVuDBioSPFdWvQe8UXgzQR60ziJD9MxQSi4C+GRkk/+6NKuvIuGx9JDQbC5KUtuPluFsgOMSo7h3O39KC7F82fI0HnHUZfsuKB8zWMEBnVs2Fcfk6c2+u0z9RSqZ/Od+lrAKoewbluQHZw6UfSgPutyPlVNOFJJj7NG3WVSJJ7dQo4JOAjFMmqVgbzDR55OFGnS7kKa9kWzkU8Tac4HyQCPrfmn7yzJyi63Yr4uZPdskbX5KUz2+zMY/VRxmHQwZAM5WGS82K4U/vA00KmmzJwuqhIAZCkJVePEVMoFXvDYW8TCM7lrOj4z3mV4JmgTj+pojb/R4Yy31l4s31SyOoZsjDlJA3UkJXhtRG4R+GtGjFQmvdbbQJ+LdEGD2pRf5iL9WD74E9LN5GGaZqy1XaYl9u0J+Xe4ArS3Eo8GUmpQKwIlXyDijTq5RZuT23Fa4fRHs2w+cMWK0wLEXD8jVQP0=
